### ISSUE TITLE
document how to use watchBuild

### ISSUE THREAD

**Issue by dlants** [neoclide/coc-tsserver#22]
It would be nice to show an example of how to use watchBuild, and what the expected behavior would be.

Currently, I have it set up like so:
```
" build and populate errors on change
autocmd User CocNvimInit call CocAction('runCommand', 'tsserver.watchBuild')
```

It seems to clear my quickfix list on file save, but I do not see project errors in the quickfix list or in `:CocList diagnostics`.

**Comment by chemzqm** [comment]
Quickfix list would be cleaned if there's no error.

Instead of autocmd, I recommend to use command like:
```
command! -nargs=0 Tsc                                  :call     CocAction('runCommand', 'tsserver.watchBuild')
```
Checkout `:h coc-status` to integrate command status to your statusline.

**Comment by chemzqm** [comment]
Use custom command instead of autocmd.

**Comment by jponc** [comment]
Hi @chemzqm , I went to this topic from https://github.com/neoclide/coc-tsserver/issues/113

I tried watchBuild but looks like it's not working? I added the following in my nvim config:

```
command! -nargs=0 Tsc :call CocAction('runCommand', 'tsserver.watchBuild')
```

But it's not showing the errors of the entire project in my quickfix view

**Comment by chemzqm** [comment]
You need invoke that command.

**Comment by jponc** [comment]
And I would expect all errors to show when I run

```
:CocList diagnostics
```

yeah? 

I tried to do the following

```
:Tsc
:CocList diagnostics
```

And it's not showing any errors even though I see them when I manually run `tsc --watch`

**Comment by jasnross** [comment]
@jponc I came across your comment while trying to figure out why `:CocList diagnostics` did not show errors from the whole project for me either. Turns out that for me errors are not populated in diagnostics but in the quickfix list, so I was just looking in the wrong place.

```
:Tsc
:copen
```

Might be nice to be able to get them in diagnostics instead since the fuzzy search feature is nice there, but at least they're available somewhere for me.

Hope it helps!

**Comment by chemzqm** [comment]
@jasnross No, it's intended, to separate lint diagnostics and compile errors.

**Comment by jponc** [comment]
@jasnross Oh wow, I was debugging this for several days now why it's not showing up in my diagnostics list. What a legend, thanks mate!

**Comment by winston164** [comment]
> Turns out that for me errors are not populated in diagnostics but in the quickfix list, so I was just looking in the wrong place.

How did you know or where did you find that the errors were being sent to the quickfix list and not the diagnostics? I also spent some time looking for a way to see project-wide errors with a react project and luckily I found this. @chemzqm I believe this should be integrated with coc-explorer since once you save a file that triggers errors in other files it should show in the explorer imo.

**Comment by buschco** [comment]
@winston164 Here is the line https://github.com/neoclide/coc-tsserver/blob/b942d76a134455a639c47ed1e6d682a7d15469dc/src/server/watchBuild.ts#L106

@chemzqm can you outline why the quickfix list is used here? Can it be configurable?

**Comment by chemzqm** [comment]
Because it's easy to use and suitable for compile errors.
It's not configurable, you can use other vim plugin like neomake to run task .

@winston164 I've added `tsserver.experimental.enableProjectDiagnostics` configuration for project wide diagnostics.
