### ISSUE TITLE
Implement inlay hints

### ISSUE THREAD

**Issue by resolritter** [neoclide/coc-tsserver#300]
Announcement: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#inlay-hints
Linked PR: https://github.com/microsoft/TypeScript/pull/42089 (was already merged)

I believe this has not yet landed on a stable release although [4.4 is scheduled for next month already](https://github.com/microsoft/TypeScript/issues/44237#issue-899908991)

**Comment by chemzqm** [comment]
It's not possible to add inline virtual text on both vim and neovim, so send your feature request to vim/neovim fist.

**Comment by resolritter** [comment]
It could work with virtual text at the end of the line in Neovim, like [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer)

**Comment by fannheyward** [comment]
I'll take a look on this after TS 4.4 released. There're several works:

1. tsserver makes its own inlayHint protocol implementation, but LSP is working on a new/standard protocol on https://github.com/microsoft/vscode-languageserver-node/pull/772
2. display with virtual text, it works but not perfect, this needs vim/nvim more works

**Comment by fannheyward** [comment]
Test code:

```ts
// enumMemberValues
enum E1 {
  A,
  B,
}

enum E2 {
  A = 0,
  B = 1,
}

// functionLikeReturnTypes
function foo() {
  return Date.now()
}

function bar(): number {
  return Date.now()
}

// parameterNames
parseInt('123', 8)

// parameterTypes
document.addEventListener('click', e => {
  console.log(e)
})

// propertyDeclarationTypes
class Bar {
  prop = Date.now;
}

// variableTypes
const xxf = Date.now()
```

In VSCode:

<img width="563" alt="截屏2021-08-09 下午6 26 39" src="https://user-images.githubusercontent.com/345274/128692853-ff24e05a-4c83-405d-af26-e0e98acad8f6.png">

In coc, only `enumMemberValues`, `functionLikeReturnTypes` and `variableTypes` are enabled.

<img width="459" alt="截屏2021-08-09 下午6 29 58" src="https://user-images.githubusercontent.com/345274/128693259-c524582c-861d-41c6-854c-62d637800c93.png">

Because we can't set inline virtual text, `parameterNames`, `parameterTypes` and `propertyDeclarationTypes` are disabled.

@chemzqm any thoughts on this? Do we need to add this in coc-tsserver?

**Comment by fannheyward** [comment]
The `variableTypes` hints should be disabled too.

**Comment by hadnet** [comment]
How is this going, guys? Any updates? When can we use this feature?

**Comment by TrietMinh799** [comment]
probably won't
